# Site settings
name: 李宣霖
location: 合肥
company: 硕士研究生
position: 机器学习/深度学习/算法工程师
github: https://github.com/yuluolin118
gitee: https://gitee.com/yuluolin118
phone: 19539903410
email: lxl1181232017@foxmail.com

title: 个人简历 - 李宣霖

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

